# Header
menu:
  主页: /
  # Delete this row if you don't want categories in your header nav bar
  目录: /categories
  归档: /archives
  关于: /about/index.html

# Content
fancybox: true

# Thumbnail
thumbnail: true

# Scroll Loading
scrollLoading: true

# Sidebar
social_links:
  twitter: https://twitter.com/wn1698
  facebook: https://www.facebook.com/profile.php?id=100009152177427
  google_plus: https://plus.google.com/u/0/108412565662276582776
  github: https://github.com/wn398
  weibo: http://weibo.com/tim398
  rss: 
widgets:
- recent_posts
- category
- archive
- tag
- tagcloud
- links

# Links
links:
  Github: https://github.com/wn398

# Miscellaneous
google_analytics:
favicon: /favicon.png
fb_admins:
fb_app_id: